//! The dense operand load: a contraction weight held as stored (f32, or BF16/F16 checkpoint bytes packed
//! two per `u32` word), read in the orientation the request names.

use poot_kernel_ir::{BinOp, Body, Local, Ty};
use poot_target::BufferStorage;

use super::Schedule;
use super::gemv::{GemvLaunch, gemv_body};
use crate::KernelGenError;
use crate::emit::{Emit, bin, copy};
use crate::helpers::{Alloc, WeightLane, WeightLayout, ld, local, slice_dtype, slice_f32};

/// How a dense contraction reads its weight: the planned storage of the weight buffer and its orientation. It
/// is part of the request, so a body built for one storage or orientation is never served for another.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct DenseLoad {
    pub(crate) weight: BufferStorage,
    pub(crate) layout: WeightLayout,
}

/// The body of a dense contraction under `schedule` with contraction depth `k`, params `(activation, weight,
/// metadata, out)`, `metadata = [K, N]` (the body reads both per call; `k` only fixes whether a packed weight's
/// row runs start on a word boundary, so the planner passes the same `K` it generated for).
///
/// - `Gemv` over `[N, K]`: the shared Gemv loop nest, each lane reading runs of its output column's
///   contiguous weight row through [`WeightLane::emit_run`].
/// - `Gemv` over `[K, N]`: refused. One workgroup per output column would read the weight at
///   a stride of `N` elements per lane, the access pattern card 035 removed.
/// - `Tiled`: refused. A dense tiled contraction is `tiled_region` (`ContractionSpec::DenseTiled`) until
///   POOT-728 serves both loads from one Tiled body.
pub(crate) fn dense_contraction(
    name: &str,
    load: DenseLoad,
    schedule: Schedule,
    k: usize,
) -> Result<Body, KernelGenError> {
    let lane = WeightLane::of("dense_contraction", load.weight)?;
    match (schedule, load.layout) {
        (Schedule::Gemv { .. }, WeightLayout::Kn) => Err(KernelGenError::Unsupported {
            request: "dense_contraction",
            reason: "a Gemv over a [K, N] weight reads it at a stride of N elements per lane",
        }),
        (
            Schedule::Gemv {
                width,
                cols,
                unroll,
            },
            WeightLayout::Nk,
        ) => Ok(dense_gemv(
            name,
            lane,
            GemvLaunch::new(width, cols, unroll)?,
            k,
        )),
        (Schedule::Tiled { .. }, _) => Err(KernelGenError::Unsupported {
            request: "dense_contraction",
            reason: "a dense Tiled contraction is generated by tiled_region (DenseTiled)",
        }),
    }
}

/// `out[n] = sum over k of activation[b, k] * weight[n, k]` over an `[N, K]` weight in `lane`'s storage: the
/// Gemv loop nest with a dense run read. Weight row `n` starts at element `n * K`, so with `K` a multiple of
/// the lane's elements per word every run of a whole number of words starts on a word boundary and loads
/// whole words; a run that does not (an odd `K`, or the one-element tail) reads element by element.
fn dense_gemv(name: &str, lane: WeightLane, launch: GemvLaunch, k: usize) -> Body {
    let al = Alloc::new(vec![
        ld(Ty::Unit, false),
        ld(slice_f32(false), false),
        lane.param(),
        ld(slice_dtype(Ty::U32, false), false),
        ld(slice_f32(true), true),
    ]);
    let (activation, weight, metadata, out) = (local(1), local(2), local(3), local(4));
    let per_word = lane.per_word();
    let rows_aligned = k.is_multiple_of(per_word);
    // `gemv_body`'s shared run-read signature: only the planar packed front end reads `out_total`.
    let read_run =
        |e: &mut Emit, row: Local, k0: Local, count: usize, k: Local, _out_total: Local| {
            let row_base = bin(e, Ty::Usize, BinOp::Mul, copy(row), copy(k));
            let first = bin(e, Ty::Usize, BinOp::Add, copy(row_base), copy(k0));
            let word_aligned = rows_aligned && count.is_multiple_of(per_word);
            lane.emit_run(e, weight, first, count, word_aligned)
        };
    gemv_body(name, al, 4, [activation, metadata, out], launch, read_run)
}
