import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// The docs sidebar is generated from the folder structure under ./docs.
// Order is controlled by _category_.json (per section) and sidebar_position
// frontmatter / numeric filename prefixes (per page).
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
